embeddings_model:
  open_ai:
    token: "..."
    embed_model: "text-embedding-3-small"
database:
  dbname: 'langchain'
  user: 'langchain'
  password: 'langchain'
  host: 'localhost'
  port: '6024'
  container_name: 'pgvector-container'
  connection_string: "postgresql+psycopg://langchain:langchain@localhost:6024/langchain"
quering:
  basic_collection_name: "general"
  k: 10
retrieve_model:
  open_ai:
    token: "..."
    model: "gpt-4o-mini"
conversations:
  trim_limit: 2
